### ISSUE TITLE
Unexpected behavior in v2

### ISSUE THREAD

**Issue by cschol** [SteveRussell33/Prism#1]
Prism v2.3.1 on Rack 2.0.0

- Channels are locked by default on startup. This is not how the SMR works and it very annoying for workflow.
- Channel Q 3-6 cannot be turned off, therefore the Global Q looks like it is not working (never achieving full resonance).

Sometimes (!) the module works correct when starting up or other channel numbers don't work. ~~I wonder if there are~~ The problem are **very likely** uninitialized variables for the channel locks and channel Qs.

**Comment by SteveRussell33** [comment]
Can you give me some more info, possibly a patch? I'm testing a fix for 1 but can't replicate 2.

**Comment by SteveRussell33** [comment]
Looks to be fixed in v2.3.3
