### ISSUE TITLE
Shouldn't Rainbow have a reset button/input?

### ISSUE THREAD

**Issue by flarn2006** [SteveRussell33/Prism#16]
I was messing with the "Lock Note" controls while having a clock connected to one of the rotate triggers. As a result, the notes were no longer lined up in a row. But I can't find any way to reset this, aside from reloading. Is this feature missing or am I the one that's missing something?

**Comment by SteveRussell33** [comment]
The original hardware doesn't have this feature and so the port doesn't either. 
I have a testing patch that uses one of the rotate triggers (clocked with a BogAudio ADDR-SEQ) and if I lock any of the filters the Rotation, Spread, Freq Nudge, Scale for that channel(s) doesn't change until unlocked again either manually using the top buttons or the CV locks at the bottom right of the panel. This is how the firmware behaves and I've not made any mods.
With my testing patch I can sometimes get it back to the original notes if I play with the locks in a performance-like manner, it's tricky but fun. Better to try using the Spread knob with Morph <50%
