### ISSUE TITLE
2.3.2 version doesn't work right as a VST plugin in Bitwig

### ISSUE THREAD

**Issue by zip0611** [SteveRussell33/Prism#2]
The scale and note functions/buttons/inputs to the right do nothing(in the rack, they do)
Lock notes can't be unlocked.

I like this module, a couple of fixes would be appreciated.

**Comment by SteveRussell33** [comment]
Have you tried the v2.3.3 update?

**Comment by zip0611** [comment]
Updated to v2.3.3 and VCV Rack Pro 2.0.3b. Fixed!

Thanks.

Zip
