### ISSUE TITLE
Artwork license

### ISSUE THREAD

**Issue by dromer** [SteveRussell33/Prism#3]
Hey there, we are working on including Prism modules into Cardinal, however we'd like to make an overview of all licensing used and the `CC BY-SA` license version is not specified.

See an overview of versions here: https://scancode-licensedb.aboutcode.org/?search=cc-by-sa

**Comment by dromer** [comment]
I suppose we should ask `Pierre Collard` about this?

**Comment by SteveRussell33** [comment]
Yes you should. You can PM him via the community forum https://community.vcvrack.com/u/pyer or email design@pierrecollard.com

**Comment by dromer** [comment]
Thnx!

**Comment by SteveRussell33** [comment]
I've update the readme to include the version number of the CC SA license, having being contacted by Pyer.

**Comment by dromer** [comment]
Thnx! I had sent them an email too, but good to know this is resolved :)
